// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgQ-5KonWczrdYgj768ZyXAUhvsGC6sRc',
    appId: '1:460482601352:web:22197d4fe36be6bf7cda3d',
    messagingSenderId: '460482601352',
    projectId: 'blogapp-448d9',
    authDomain: 'blogapp-448d9.firebaseapp.com',
    storageBucket: 'blogapp-448d9.firebasestorage.app',
    measurementId: 'G-JY41M7PWXT',
    databaseURL: 'https://blogapp-448d9-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE10rjZ5mBC1P6_UBkkO9Pa3BZ5ihwf9I',
    appId: '1:460482601352:android:8395395ba279ceb57cda3d',
    messagingSenderId: '460482601352',
    projectId: 'blogapp-448d9',
    storageBucket: 'blogapp-448d9.firebasestorage.app',
    databaseURL: 'https://blogapp-448d9-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuUB-jm60dE_nLpi0sKBs1js-9LrmZwlE',
    appId: '1:460482601352:ios:4b91b0f0658d1b977cda3d',
    messagingSenderId: '460482601352',
    projectId: 'blogapp-448d9',
    storageBucket: 'blogapp-448d9.firebasestorage.app',
    iosBundleId: 'com.santosenoque.firebaseCourse',
    databaseURL: 'https://blogapp-448d9-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgQ-5KonWczrdYgj768ZyXAUhvsGC6sRc',
    appId: '1:460482601352:web:dfd7248a46abc2187cda3d',
    messagingSenderId: '460482601352',
    projectId: 'blogapp-448d9',
    authDomain: 'blogapp-448d9.firebaseapp.com',
    storageBucket: 'blogapp-448d9.firebasestorage.app',
    measurementId: 'G-WMZ3VM9KDD',
    databaseURL: 'https://blogapp-448d9-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
